image: node
stages:
  - build
before_script:
  - yarn install
build chromium:
  stage: build
  script:
    # TODO how about include reports? IDK how tho.
    # https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#artifactsreports
    - yarn build:chromium --env noreport
  artifacts:
    paths:
      - dist/
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  timeout: 10 minutes
build gecko:
  stage: build
  # TODO DRY with `build chromium`? YAML anchors?
  script:
    - yarn build:gecko --env noreport
  artifacts:
    paths:
      - dist/
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  timeout: 10 minutes
